### ISSUE TITLE
documentation for the master branch doesn't update. 

### ISSUE THREAD

**Issue by petr-tik** [quickwit-oss/tantivy#546]
Hey, I think our doc pages for the master branch aren't updating. 

We added a separate opstamp type in the last commit and it's not reflected in documentation on the master branch. 
https://github.com/tantivy-search/tantivy/blob/master/src/lib.rs#L265

Follow me to reproduce.

***Reproduce***

Go to [readme/getting started section](https://github.com/tantivy-search/tantivy#getting-started)

Follow the link [to docs for the last master branch](https://tantivy-search.github.io/tantivy/tantivy/index.html)

Run the query below
https://tantivy-search.github.io/tantivy/tantivy/index.html?search=opstamp

**What happened?**
Only shows methods with opstamp in the name. 

**What was expected?**
type Opstamp should also show up. 

**Which version of tantivy are you using?**
master
https://github.com/tantivy-search/tantivy/commit/5c0b2a4579adbdbb0c87adefa67bae0aa729c620

**Info that might help**
the gh-pages branch was last updated nearly a year ago
https://github.com/tantivy-search/tantivy/tree/gh-pages

I am struggling to see where in travis.yml documentation is generated and updated.

**Comment by petr-tik** [comment]
I think I found the culprit. 

https://github.com/tantivy-search/tantivy/commit/09661ea7ec9b8f26dcff8ac07b8ac260c37c7f2d

Removes uploading documents. Should be easy to include again (famous last words). Will poke at it, when I have time

**Comment by fulmicoton** [comment]
Nice job spotting it. I tried to read the `cargo doc-upload` thing. Let's see what happens.

**Comment by petr-tik** [comment]
docs aren't updated due to the failure in the CI build and cargo doc-upload running after_success 

Also, cargo doc-upload seems not to work as expected. See the bottom of the [travis build log](https://api.travis-ci.org/v3/job/538509387/log.txt)

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/tantivy-search/tantivy.git/'
Documentation already up-to-date.

```

**Comment by petr-tik** [comment]
Can we agree on the best way to update documentation, before we implement this? 

The head of master branch progresses in 2 different ways:
1. One of the contributors commits directly to master
2. a PR is merged via Git or GitHub by Paul 

in (2), using cargo-travis won't help us, as it skips upload documentation from PRs.

**Comment by fulmicoton** [comment]
I'm ok with this.

The master branch is already protected. I'm the only person who can unprotect it.
I did unprotect that branch to amend a commit in master right after I merged a branch, but this is super rare.

**Comment by petr-tik** [comment]
Looking at the last 10 lines of [most recent travis-log from a push build ](https://api.travis-ci.org/v3/job/544505108/log.txt)

```bash
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/tantivy-search/tantivy.git/'
```

We need to set authentication travis to push to gh-pages. I don't have access to the travis config for tantivy, but I imagine there must be a way to do this and restrict it to the `gh-pages` branch

https://help.github.com/en/articles/enabling-branch-restrictions

**Comment by fulmicoton** [comment]
Ok I fixed it. I did a bunch of thing, but I think what fixed it is removing the encrypted environment and set a brand new token via the travis interface instead.

Also I disabled doc building and uploading on all platforms but one.

**Comment by petr-tik** [comment]
Running the query below still fails to find Opstamp as a type
https://tantivy-search.github.io/tantivy/tantivy/index.html?search=opstamp

Our top-level directory on gh-pages looks like this

```bash
aho-corasick - updated last year
ascii - updated last year
...
master - updated 12 hours ago
...
winapi - updated last year
```

Upon inspection it looks like documentation is written to the `master/tantivy` [directory on gh-pages](https://github.com/tantivy-search/tantivy/tree/gh-pages/master/tantivy), which makes our directory look like this 

```bash
aho-corasick - updated 12 hours ago
ascii - updated 12 hours ago
...
winapi - updated 12 hours ago
```

**Comment by bedax** [comment]
I'm new to tantivy and was confused why the docs don't reflect changes that seemed to have happened a while ago in the issue tracker. There's a big difference between this: https://tantivy-search.github.io/tantivy/tantivy/query/index.html and this: https://docs.rs/tantivy/0.10.0/tantivy/query/index.html

Perhaps as a temporary fix, while your github.io docs are being fixed, you could change the doc links to point to docs.rs?

**Comment by fulmicoton** [comment]
Removed master docs entirely from the links.
